# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Farmhub < Formula
  desc ""
  homepage "https://farmhub.ag"
  version "1.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.1.1/farmhub_Darwin_x86_64.tar.gz"
      sha256 "f9d458be8d0c26e7ae8f4495e011b6ac4be5d627113e08eb335a27aea85942de"

      def install
        bin.install "farmhub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.1.1/farmhub_Darwin_arm64.tar.gz"
      sha256 "e807521fc7ca5221b4964be3c13d08893994d7145fea6d94c57bba3bd0075f87"

      def install
        bin.install "farmhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.1.1/farmhub_Linux_arm64.tar.gz"
      sha256 "1d71926ba6222ec066745db8472940152762930260e3a6e6b8a79d4565455165"

      def install
        bin.install "farmhub"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.1.1/farmhub_Linux_x86_64.tar.gz"
      sha256 "1d31c64acbdea164e1263115755dccb96c65fefc3eabcd90fa4a6493c6f1e3b3"

      def install
        bin.install "farmhub"
      end
    end
  end

  test do
    system "#{bin}/farmhub version"
  end
end
