# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Farmhub < Formula
  desc ""
  homepage "https://farmhub.ag"
  version "1.5.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.5.14/farmhub_Darwin_x86_64.tar.gz"
      sha256 "601f9cf92f3a5a01574c3a73a5225857cbfa45e357bd59ef974719c88593ffb9"

      def install
        bin.install "farmhub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.5.14/farmhub_Darwin_arm64.tar.gz"
      sha256 "26ce9aad5771a6d18f3edc7c206f0716dffd5390bce5449e15b194da6919c296"

      def install
        bin.install "farmhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.5.14/farmhub_Linux_x86_64.tar.gz"
      sha256 "8c8191c138c6f63e644f087ab5917ece5b12249c662c7decc46ca9794befe893"

      def install
        bin.install "farmhub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.5.14/farmhub_Linux_arm64.tar.gz"
      sha256 "5da31f81632e95c2119095d04128ba50b19578b9cb54824361dfd75dc92d370f"

      def install
        bin.install "farmhub"
      end
    end
  end

  test do
    system "#{bin}/farmhub version"
  end
end
