# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Farmhub < Formula
  desc ""
  homepage "https://farmhub.ag"
  version "1.5.13"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.5.13/farmhub_Darwin_arm64.tar.gz"
      sha256 "39b21429b948b3c2a1819356e82ffeced18b1a0acacb1eb1268f7c9b65ec006f"

      def install
        bin.install "farmhub"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.5.13/farmhub_Darwin_x86_64.tar.gz"
      sha256 "4d0c74f6147ffb5c0c2775d5545594b6bac7cf31fdd66d844e8ae13635ea0463"

      def install
        bin.install "farmhub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.5.13/farmhub_Linux_arm64.tar.gz"
      sha256 "560dcb69c020d239482be1cc41d9542face315b9761bbcb62dce6bcabe70a19c"

      def install
        bin.install "farmhub"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/thefarmhub/farmhub-cli/releases/download/v1.5.13/farmhub_Linux_x86_64.tar.gz"
      sha256 "04e73a0bda76d00e20942d4b3673ef8493c3610646ee1fede1c7ecda4daa9dcb"

      def install
        bin.install "farmhub"
      end
    end
  end

  test do
    system "#{bin}/farmhub version"
  end
end
